spring:
  application:
    name: employee-management
  datasource:
    #    url: jdbc:h2:file:./src/main/resources/data/employee-management;MODE=PostgreSQL;
    url: jdbc:mysql:localhost:3306/Employee-management
    username: sa
    password: Admin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #      naming:
    #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        #        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 1000